name: Crear PR autom치tico
on:
  workflow_dispatch: {}
  push:
    branches: [main]   # ejecuta al hacer push a main (puedes cambiarlo)
  schedule:
    - cron: "0 12 * * 1"   # opcional: lunes 12:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  crear-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar autor del commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 游녤 Simula un cambio
      - name: Generar cambio
        run: |
          echo "Actualizado por bot: $(date -u)" >> AUTOGEN.md

      - name: Actualizar rama remota antes de push
        run: |
          git fetch origin bot/auto-actualizacion || true
          git checkout -B bot/auto-actualizacion
          git merge origin/bot/auto-actualizacion || true
          git add -A
          git commit -m "chore(bot): actualizaci칩n autom치tica" || echo "Nada que commitear"
          git push -u origin bot/auto-actualizacion

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/auto-actualizacion
          title: "chore(bot): actualizaci칩n autom치tica"
          body: "PR creado autom치ticamente por el workflow."
          commit-message: "chore(bot): actualizaci칩n autom치tica"
          labels: bot, automatizado
          assignees: jhonmario-argumedo
